theme: jekyll-theme-minimal
title: [Hey it's Juliana!]
description: [Keep track of the things I'm wokring on!]
collections:
  parts:
    output: true
defaults:
  - scope:
      path: ""
      type: parts
  values:
    layout: default

